export const HOMEWORK_RANGE_NAMES = [
    'STUDENT_FIRST_NAMES', 
    'STUDENT_LAST_NAMES',
    'STUDENT_EMAILS', 
    'HOMEWORK_LESSONS',
    'HOMEWORK_NAMES',
    'HOMEWORK_DUE_DATES',
    'HOMEWORK_COMPLETION',
];

